/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package th1604.bai3jlist;

import java.awt.*;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author trong
 */
public class Bai3TH1604 extends javax.swing.JFrame {

    /**
     * Creates new form Bai3TH1604
     */
    DefaultListModel mTrai;
    DefaultListModel mPhai;

    public Bai3TH1604() {
        initComponents();
        mTrai = new DefaultListModel();
        listMonTheThao.setModel(mTrai);

        mTrai.addElement("Bóng Đá");
        mTrai.addElement("Cầu lông");
        mTrai.addElement("Karatedo");
        mTrai.addElement("Bóng chuyền");

        mPhai = new DefaultListModel();
        mPhai.addElement("Fifa Online");
        listMonYeuThich.setModel(mPhai);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbDSMonTheThao = new javax.swing.JLabel();
        lbMonYeuThich = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listMonTheThao = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listMonYeuThich = new javax.swing.JList<>();
        btAdd = new javax.swing.JButton();
        btAddAll = new javax.swing.JButton();
        btRemove = new javax.swing.JButton();
        btRemoveAll = new javax.swing.JButton();
        btThem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbDSMonTheThao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbDSMonTheThao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDSMonTheThao.setText("Danh sách môn thể thao");

        lbMonYeuThich.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbMonYeuThich.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMonYeuThich.setText("Môn yêu thích");

        listMonTheThao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(listMonTheThao);

        listMonYeuThich.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jScrollPane2.setViewportView(listMonYeuThich);

        btAdd.setText(">");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btAddAll.setText(">>");
        btAddAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddAllActionPerformed(evt);
            }
        });

        btRemove.setText("<");
        btRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveActionPerformed(evt);
            }
        });

        btRemoveAll.setText("<<");
        btRemoveAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveAllActionPerformed(evt);
            }
        });

        btThem.setText("+");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbDSMonTheThao, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAddAll, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRemoveAll, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRemove, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMonYeuThich, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDSMonTheThao, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMonYeuThich, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAddAll, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRemoveAll, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        String input = JOptionPane.showInputDialog("Nhập tên môn thể thao: ");
        mTrai.addElement(input);

//        ListModel dsMonTheThao = listMonTheThao.getModel();
//
//        ArrayList<String> arrMonTheThao = new ArrayList<>();
//        int i = 0, n = dsMonTheThao.getSize();
//        for (i = 0; i < n; i++) {
//            String ten = dsMonTheThao.getElementAt(i).toString();
//            arrMonTheThao.add(ten);
//        }
//        arrMonTheThao.add(input);
//        //Chuyển sang kiểu mảng để đưa vào JList
//        String[] mMonTheThao = arrMonTheThao.toArray(new String[0]);
//        listMonTheThao.setListData(mMonTheThao);
    }//GEN-LAST:event_btThemActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed

        int[] indexs = listMonTheThao.getSelectedIndices();
        for (int i = indexs.length - 1; i >= 0; i--) {
            mPhai.addElement(mTrai.get(indexs[i]));
            mTrai.remove(indexs[i]);
        }


    }//GEN-LAST:event_btAddActionPerformed

    private void btAddAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddAllActionPerformed
        int m = mTrai.getSize();
        for (int i = 0; i < m; i++) {
            mPhai.addElement(mTrai.get(i));
        }
            mTrai.clear();
    }//GEN-LAST:event_btAddAllActionPerformed

    private void btRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveActionPerformed
        int[] indexs = listMonYeuThich.getSelectedIndices();
        for (int i = indexs.length - 1; i >= 0; i--) {
            mTrai.addElement(mPhai.get(indexs[i]));
            mPhai.remove(indexs[i]);
        }
    }//GEN-LAST:event_btRemoveActionPerformed

    private void btRemoveAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveAllActionPerformed
       int n = mPhai.getSize();
       for(int i = 0; i < n; i++){
           mTrai.addElement(mPhai.get(i));
       }
       mPhai.clear();
    }//GEN-LAST:event_btRemoveAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai3TH1604.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai3TH1604.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai3TH1604.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai3TH1604.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai3TH1604().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btAddAll;
    private javax.swing.JButton btRemove;
    private javax.swing.JButton btRemoveAll;
    private javax.swing.JButton btThem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbDSMonTheThao;
    private javax.swing.JLabel lbMonYeuThich;
    private javax.swing.JList<String> listMonTheThao;
    private javax.swing.JList<String> listMonYeuThich;
    // End of variables declaration//GEN-END:variables
}
