/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author trong
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        tabQLBH = new javax.swing.JTabbedPane();
        tabQLNhanVien = new javax.swing.JLayeredPane();
        lbMaNhanVien = new javax.swing.JLabel();
        txtMaNhanVien = new javax.swing.JTextField();
        lbTenHang1 = new javax.swing.JLabel();
        txtTenNhanVien = new javax.swing.JTextField();
        lbGioiTinh = new javax.swing.JLabel();
        lbDiaChi = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        lbNgaySinh = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        lbDienThoai = new javax.swing.JLabel();
        txtDienThoai = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        btThemNV = new javax.swing.JButton();
        btXoaNV = new javax.swing.JButton();
        btSuaNV = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        tabQLKhachHang = new javax.swing.JLayeredPane();
        lbMaKhach = new javax.swing.JLabel();
        txtMaKhach = new javax.swing.JTextField();
        lbTenKhach = new javax.swing.JLabel();
        txtTenKhach = new javax.swing.JTextField();
        lbDiaChiKH = new javax.swing.JLabel();
        txtDiaChiKH = new javax.swing.JTextField();
        lbSDT = new javax.swing.JLabel();
        txtDienThoaiKH = new javax.swing.JTextField();
        btThemKH = new javax.swing.JButton();
        btXoaKH = new javax.swing.JButton();
        btSuaKH = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        tabQLHoaDon = new javax.swing.JLayeredPane();
        tabQLMatHang = new javax.swing.JLayeredPane();
        lbMaHang = new javax.swing.JLabel();
        txtMaHang = new javax.swing.JTextField();
        txtTenHang = new javax.swing.JTextField();
        lbTenHang = new javax.swing.JLabel();
        lbMaChatLieuFk = new javax.swing.JLabel();
        txtMaChatLieuFk = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        lbSoLuong = new javax.swing.JLabel();
        lbDonGiaNhap = new javax.swing.JLabel();
        txtDonGiaNhap = new javax.swing.JTextField();
        lbDonGiaBan = new javax.swing.JLabel();
        txtDonGiaBan = new javax.swing.JTextField();
        lbAnh = new javax.swing.JLabel();
        txtAnh = new javax.swing.JTextField();
        lbGhiChu = new javax.swing.JLabel();
        txtGhiChu = new javax.swing.JTextField();
        btThemMH = new javax.swing.JButton();
        btXoaMH = new javax.swing.JButton();
        btSuaMH = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        tabQLChatLieu = new javax.swing.JLayeredPane();
        txtMaChatLieu = new javax.swing.JTextField();
        lbMaChatLieu = new javax.swing.JLabel();
        lbTenChatLieu = new javax.swing.JLabel();
        txtTenChatLieu = new javax.swing.JTextField();
        btThem = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbMaNhanVien.setText("Mã Nhân Viên");

        lbTenHang1.setText("Tên Nhân Viên");

        lbGioiTinh.setText("Giới Tính");

        lbDiaChi.setText("Địa Chỉ");

        lbNgaySinh.setText("Ngày Sinh");

        lbDienThoai.setText("Điện Thoại");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        btThemNV.setText("Thêm");

        btXoaNV.setText("Xoá");

        btSuaNV.setText("Sửa");

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Nhân Viên ", "Tên Nhân Viên", "Giới Tính", "Địa Chỉ", "Ngày Sinh", "Điện Thoại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable6);

        tabQLNhanVien.setLayer(lbMaNhanVien, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLNhanVien.setLayer(txtMaNhanVien, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLNhanVien.setLayer(lbTenHang1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLNhanVien.setLayer(txtTenNhanVien, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLNhanVien.setLayer(lbGioiTinh, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLNhanVien.setLayer(lbDiaChi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLNhanVien.setLayer(txtDiaChi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLNhanVien.setLayer(lbNgaySinh, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLNhanVien.setLayer(txtNgaySinh, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLNhanVien.setLayer(lbDienThoai, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLNhanVien.setLayer(txtDienThoai, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLNhanVien.setLayer(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLNhanVien.setLayer(btThemNV, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLNhanVien.setLayer(btXoaNV, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLNhanVien.setLayer(btSuaNV, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLNhanVien.setLayer(jScrollPane6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout tabQLNhanVienLayout = new javax.swing.GroupLayout(tabQLNhanVien);
        tabQLNhanVien.setLayout(tabQLNhanVienLayout);
        tabQLNhanVienLayout.setHorizontalGroup(
            tabQLNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabQLNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabQLNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabQLNhanVienLayout.createSequentialGroup()
                        .addGroup(tabQLNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabQLNhanVienLayout.createSequentialGroup()
                                .addGroup(tabQLNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tabQLNhanVienLayout.createSequentialGroup()
                                        .addComponent(lbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(tabQLNhanVienLayout.createSequentialGroup()
                                        .addComponent(lbMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMaNhanVien)))
                                .addGap(18, 18, 18)
                                .addGroup(tabQLNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbDiaChi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbTenHang1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(tabQLNhanVienLayout.createSequentialGroup()
                                .addComponent(lbNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNgaySinh)
                                .addGap(18, 18, 18)
                                .addComponent(lbDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabQLNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDienThoai)
                            .addComponent(txtTenNhanVien)
                            .addComponent(txtDiaChi)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabQLNhanVienLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btThemNV, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btXoaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSuaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        tabQLNhanVienLayout.setVerticalGroup(
            tabQLNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabQLNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabQLNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTenHang1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabQLNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabQLNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabQLNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThemNV, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btXoaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSuaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabQLBH.addTab("Quản Lý Nhân Viên", tabQLNhanVien);

        lbMaKhach.setText("Mã Khách Hàng");

        lbTenKhach.setText("Tên Khách Hàng");

        lbDiaChiKH.setText("Địa Chỉ");

        lbSDT.setText("Số Điện Thoại");

        btThemKH.setText("Thêm");

        btXoaKH.setText("Xoá");

        btSuaKH.setText("Sửa");

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Khách Hàng", "Tên Khách Hàng", "Địa Chỉ", "Số Điện Thoại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jTable7);

        tabQLKhachHang.setLayer(lbMaKhach, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLKhachHang.setLayer(txtMaKhach, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLKhachHang.setLayer(lbTenKhach, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLKhachHang.setLayer(txtTenKhach, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLKhachHang.setLayer(lbDiaChiKH, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLKhachHang.setLayer(txtDiaChiKH, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLKhachHang.setLayer(lbSDT, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLKhachHang.setLayer(txtDienThoaiKH, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLKhachHang.setLayer(btThemKH, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLKhachHang.setLayer(btXoaKH, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLKhachHang.setLayer(btSuaKH, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLKhachHang.setLayer(jScrollPane7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout tabQLKhachHangLayout = new javax.swing.GroupLayout(tabQLKhachHang);
        tabQLKhachHang.setLayout(tabQLKhachHangLayout);
        tabQLKhachHangLayout.setHorizontalGroup(
            tabQLKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabQLKhachHangLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btThemKH, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btXoaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSuaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(tabQLKhachHangLayout.createSequentialGroup()
                .addGroup(tabQLKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabQLKhachHangLayout.createSequentialGroup()
                        .addComponent(lbDiaChiKH, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDiaChiKH, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                    .addGroup(tabQLKhachHangLayout.createSequentialGroup()
                        .addComponent(lbMaKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaKhach)))
                .addGap(38, 38, 38)
                .addGroup(tabQLKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSDT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTenKhach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabQLKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenKhach)
                    .addComponent(txtDienThoaiKH, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)))
            .addComponent(jScrollPane7)
        );
        tabQLKhachHangLayout.setVerticalGroup(
            tabQLKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabQLKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabQLKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTenKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabQLKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDiaChiKH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiaChiKH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDienThoaiKH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabQLKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThemKH, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btXoaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSuaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        tabQLBH.addTab("Quản lý Khách Hàng", tabQLKhachHang);

        javax.swing.GroupLayout tabQLHoaDonLayout = new javax.swing.GroupLayout(tabQLHoaDon);
        tabQLHoaDon.setLayout(tabQLHoaDonLayout);
        tabQLHoaDonLayout.setHorizontalGroup(
            tabQLHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
        );
        tabQLHoaDonLayout.setVerticalGroup(
            tabQLHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
        );

        tabQLBH.addTab("Quản Lý Hoá Đơn", tabQLHoaDon);

        lbMaHang.setText("Mã Hàng");

        lbTenHang.setText("Tên Hàng");

        lbMaChatLieuFk.setText("Mã Chất Liệu");

        lbSoLuong.setText("Số Lượng");

        lbDonGiaNhap.setText("Đơn Giá Nhập");

        lbDonGiaBan.setText("Đơn Giá Bán");

        lbAnh.setText("Ảnh");

        lbGhiChu.setText("Ghi Chú");

        btThemMH.setText("Thêm");

        btXoaMH.setText("Xoá");

        btSuaMH.setText("Sửa");

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Hàng", "Tên Hàng", "Mã Chất Liệu", "Tên Chất Liệu", "Đơn Giá Nhập", "Đơn Giá Bán", "Ảnh", "Ghi Chú"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable5);

        tabQLMatHang.setLayer(lbMaHang, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLMatHang.setLayer(txtMaHang, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLMatHang.setLayer(txtTenHang, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLMatHang.setLayer(lbTenHang, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLMatHang.setLayer(lbMaChatLieuFk, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLMatHang.setLayer(txtMaChatLieuFk, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLMatHang.setLayer(txtSoLuong, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLMatHang.setLayer(lbSoLuong, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLMatHang.setLayer(lbDonGiaNhap, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLMatHang.setLayer(txtDonGiaNhap, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLMatHang.setLayer(lbDonGiaBan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLMatHang.setLayer(txtDonGiaBan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLMatHang.setLayer(lbAnh, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLMatHang.setLayer(txtAnh, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLMatHang.setLayer(lbGhiChu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLMatHang.setLayer(txtGhiChu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLMatHang.setLayer(btThemMH, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLMatHang.setLayer(btXoaMH, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLMatHang.setLayer(btSuaMH, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLMatHang.setLayer(jScrollPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout tabQLMatHangLayout = new javax.swing.GroupLayout(tabQLMatHang);
        tabQLMatHang.setLayout(tabQLMatHangLayout);
        tabQLMatHangLayout.setHorizontalGroup(
            tabQLMatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabQLMatHangLayout.createSequentialGroup()
                .addGroup(tabQLMatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabQLMatHangLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(tabQLMatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabQLMatHangLayout.createSequentialGroup()
                                .addComponent(lbDonGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDonGiaNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                .addGap(38, 38, 38)
                                .addComponent(lbDonGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDonGiaBan, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                            .addGroup(tabQLMatHangLayout.createSequentialGroup()
                                .addComponent(lbAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                .addGap(38, 38, 38)
                                .addComponent(lbGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGhiChu, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabQLMatHangLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btThemMH, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btXoaMH, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btSuaMH, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tabQLMatHangLayout.createSequentialGroup()
                                .addGroup(tabQLMatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tabQLMatHangLayout.createSequentialGroup()
                                        .addComponent(lbMaChatLieuFk, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMaChatLieuFk, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                                    .addGroup(tabQLMatHangLayout.createSequentialGroup()
                                        .addComponent(lbMaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMaHang)))
                                .addGap(38, 38, 38)
                                .addGroup(tabQLMatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbSoLuong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbTenHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(tabQLMatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenHang)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)))))
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );
        tabQLMatHangLayout.setVerticalGroup(
            tabQLMatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabQLMatHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabQLMatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTenHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabQLMatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaChatLieuFk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaChatLieuFk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabQLMatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDonGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDonGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDonGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDonGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabQLMatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabQLMatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThemMH, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btXoaMH, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSuaMH, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        tabQLBH.addTab("Quản Lý Mặt Hàng", tabQLMatHang);

        lbMaChatLieu.setText("Mã Chất Liệu");

        lbTenChatLieu.setText("Tên Chất Liệu");

        btThem.setText("Thêm");

        btXoa.setText("Xoá");

        btSua.setText("Sửa");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã Chất Liệu", "Tên Chất Liệu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        tabQLChatLieu.setLayer(txtMaChatLieu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLChatLieu.setLayer(lbMaChatLieu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLChatLieu.setLayer(lbTenChatLieu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLChatLieu.setLayer(txtTenChatLieu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLChatLieu.setLayer(btThem, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLChatLieu.setLayer(btXoa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLChatLieu.setLayer(btSua, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tabQLChatLieu.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout tabQLChatLieuLayout = new javax.swing.GroupLayout(tabQLChatLieu);
        tabQLChatLieu.setLayout(tabQLChatLieuLayout);
        tabQLChatLieuLayout.setHorizontalGroup(
            tabQLChatLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabQLChatLieuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabQLChatLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tabQLChatLieuLayout.createSequentialGroup()
                        .addComponent(lbMaChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(txtMaChatLieu)
                        .addGap(43, 43, 43)
                        .addComponent(lbTenChatLieu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenChatLieu))
                    .addGroup(tabQLChatLieuLayout.createSequentialGroup()
                        .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSua, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        tabQLChatLieuLayout.setVerticalGroup(
            tabQLChatLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabQLChatLieuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabQLChatLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMaChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTenChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabQLChatLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSua, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        tabQLBH.addTab("Quản Lý Chất Liệu", tabQLChatLieu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabQLBH)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabQLBH)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSua;
    private javax.swing.JButton btSuaKH;
    private javax.swing.JButton btSuaMH;
    private javax.swing.JButton btSuaNV;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btThemKH;
    private javax.swing.JButton btThemMH;
    private javax.swing.JButton btThemNV;
    private javax.swing.JButton btXoa;
    private javax.swing.JButton btXoaKH;
    private javax.swing.JButton btXoaMH;
    private javax.swing.JButton btXoaNV;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JLabel lbAnh;
    private javax.swing.JLabel lbDiaChi;
    private javax.swing.JLabel lbDiaChiKH;
    private javax.swing.JLabel lbDienThoai;
    private javax.swing.JLabel lbDonGiaBan;
    private javax.swing.JLabel lbDonGiaNhap;
    private javax.swing.JLabel lbGhiChu;
    private javax.swing.JLabel lbGioiTinh;
    private javax.swing.JLabel lbMaChatLieu;
    private javax.swing.JLabel lbMaChatLieuFk;
    private javax.swing.JLabel lbMaHang;
    private javax.swing.JLabel lbMaKhach;
    private javax.swing.JLabel lbMaNhanVien;
    private javax.swing.JLabel lbNgaySinh;
    private javax.swing.JLabel lbSDT;
    private javax.swing.JLabel lbSoLuong;
    private javax.swing.JLabel lbTenChatLieu;
    private javax.swing.JLabel lbTenHang;
    private javax.swing.JLabel lbTenHang1;
    private javax.swing.JLabel lbTenKhach;
    private javax.swing.JTabbedPane tabQLBH;
    private javax.swing.JLayeredPane tabQLChatLieu;
    private javax.swing.JLayeredPane tabQLHoaDon;
    private javax.swing.JLayeredPane tabQLKhachHang;
    private javax.swing.JLayeredPane tabQLMatHang;
    private javax.swing.JLayeredPane tabQLNhanVien;
    private javax.swing.JTextField txtAnh;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtDiaChiKH;
    private javax.swing.JTextField txtDienThoai;
    private javax.swing.JTextField txtDienThoaiKH;
    private javax.swing.JTextField txtDonGiaBan;
    private javax.swing.JTextField txtDonGiaNhap;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtMaChatLieu;
    private javax.swing.JTextField txtMaChatLieuFk;
    private javax.swing.JTextField txtMaHang;
    private javax.swing.JTextField txtMaKhach;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenChatLieu;
    private javax.swing.JTextField txtTenHang;
    private javax.swing.JTextField txtTenKhach;
    private javax.swing.JTextField txtTenNhanVien;
    // End of variables declaration//GEN-END:variables
}
